import { Icon, getSkillIcon } from "@/_components/Icon";
import { SkillIcons } from ".";

export const iconMapping: SkillIcons = {
  typescript: <Icon name="typescript" />,
  react: <Icon name="react" />,
  javascript: <Icon name="javascript" />,
  nextjs: <Icon name="nextjs" />,
  reactspring: <Icon name="reactspring" />,
  prisma: <Icon name="prisma" />,
  trpc: <Icon name="trpc" />,
  docker: <Icon name="docker" />,
  tailwind: <Icon name="tailwind" />,
  jest: <Icon name="jest" />,
  cypress: <Icon name="cypress" />,
  reactquery: <Icon name="reactquery" />,
  redux: <Icon name="redux" />,
  zod: <Icon name="zod" />,
  formik: <Icon name="formik" />,
  axios: <Icon name="axios" />,
  linux: <Icon name="linux" />,
  testinglibrary: <Icon name="testinglibrary" />,
  vitest: <Icon name="vitest" />,
  postgresql: <Icon name="postgresql" />,
  authjs: <Icon name="authjs" />,
  spline: <Icon name="spline" />,
  vercel: <Icon name="vercel" />,
  netlify: <Icon name="netlify" />,
  githubactions: <Icon name="githubactions" />,
  githubpages: <Icon name="githubpages" />,
  reactrouter: <Icon name="reactrouter" />,
  rust: <Icon name="rust" />,
  vite: <Icon name="vite" />,
  strapi: <Icon name="strapi" />,
  sass: <Icon name="sass" />,
  api: <Icon name="api" />,
  editorjs: <Icon name="editorjs" />,
  css: <Icon name="css" />,
  html: <Icon name="html" />,
  electron: <Icon name="electron" />,
  pwa: <Icon name="pwa" />,
  themeui: <Icon name="themeui" />,
  html2canvas: <Icon name="html2canvas" />,
  reacttestinglibrary: <Icon name="reacttestinglibrary" />,
  cicd: <Icon name="cicd" />,
  xstate: <Icon name="xstate" />,
  sqlite: <Icon name="sqlite" />,
};
